### ISSUE TITLE
PING NOK since Invalid date

### ISSUE THREAD

**Issue by ThomasH-W** [AgP42/MMM-iFrame-Ping#1]
I do get an error when using the module: 
         PING NOK since Invalid date
         Update requested at : Do. - 21:40:34

System: Raspberry 3 based on Stretch
             Localisation Options: de-DE.UTF-8 UTF-8 auswählen

I do see the picture/stream when using the url in a chrome web-browser

config.js:
```
var config = {
	language: 'de',
	timeFormat: 24,
	units: "metric",
	modules: [
		{   // ------------------------------------------------------------------------ module
			module: 'MMM-iFrame-Ping',
				position: 'middle_center',	// This can be any of the regions.
				config: {
					// See 'Configuration options' for more information.
					url: "https://video.nest.com/embedded/live/wSbs3mRsOF?autoplay=1",
					height:"100%", 
					width:"100%",
					autoRefresh: true, //set to false for video
					updateInterval: 1, //in min. Only if autoRefresh: true
					displayLastUpdate:  true,
					width: "100%", // Optional. Default: 100%
					height: "400px", //Optional. Default: 100px
					scrolling: "no" 
				}
		}, // end of module
	]
};
```

**Comment by AgP42** [comment]
Hello, 
the problem is that is seams that NEST server refuses to answer to ping, as you can see bellow (google answers, not nest...)
![image](https://user-images.githubusercontent.com/12719820/44280437-0be0c580-a255-11e8-9beb-23cf5d6c1401.png)
So you will not be able to use my module with nest camera... 

I will update the readme file and the description of it. 

I advice you to test one of the other iFrame module, [see here](https://github.com/AgP42/MMM-iFrame-Ping#other-iframe-modules)

Sorry and good luck :-)

**Comment by ThomasH-W** [comment]
Thanks for the quick response.
I did a reboot of the system.
Now the error message is still visible for a while but then the page gets loaded.

**Comment by AgP42** [comment]
Hello, 

on the next version (no idea when, sorry...), I will add a parameter to remove the "ping" request, this will probably solve your problem

Bye,

**Comment by ThomasH-W** [comment]
Take your time, this is not a priority.
Anyway, thanks for sharing this module.
