### ISSUE TITLE
2 frames issues

### ISSUE THREAD

**Issue by ghost** [AgP42/MMM-iFrame-Ping#2]
Hello!

Thank you for your module.

When I try to have 2 different frame at the same time (different positions) it doesn't works.

The first one is showing the second one, and the second is loading perpetually.

Any idea on how to change that?

**Comment by AgP42** [comment]
Hello, 

yes, the management of several instances is not supported, this is probably due to the use of a single "node_helper" file. Please see [this post](https://forum.magicmirror.builders/topic/8499/solved-several-module-instances-with-one-node_helper). 
Unfortunatelly, I never success to make it working properly on another MM module, so I didn't implement it on this module... 
Another idea, if you are not interested on the functionnalities of "data optimisation", you can also try to comment all the functions "suspend", "resume", "notificationReceived" and "GestionUpdateIntervaliFrame", sometime the "resume" function is called by MM core and it create some disorder...

Let me know and feel free to propose a pull request if you were able to solve it.  

Bye

**Comment by ghost** [comment]
Thank you for your answer. I've find another "solution" which is building a custom webpage before showing it on the mirror, so I have now only one page to load.
