### ISSUE TITLE
how to scale the page that is shown?

### ISSUE THREAD

**Issue by Felisuk** [AgP42/MMM-iFrame-Ping#6]
Thanks for sharing this module.

I´ve been tried and I wonder if there any way to scale the web, I can scrolling but I don´t if It would be possible scaling the page.

Thanks in advance.

**Comment by AgP42** [comment]
Hello, 

you can theoretically do it, for example [here](http://jsfiddle.net/AwokeKnowing/yy8yb/), or search on google how to scale an iFrame, but I personally didn't succeed to do it on the MM...
(I succeed to scale a website for test session on jsfiddle, but the same code doesn't works on the MM)
I guess it is due to the javascript version used by the MagicMirror, but not sure. 

So it may work on the future when the MM will be uploaded with a newer JS version. 

So for now I don't see any solution, sorry, 

Bye, 
AgP42

**Comment by Felisuk** [comment]
Hello,  and thanks for the answer, at least I'll stop thinking about it.
